title: My GitHub Pages Site
description: A personal website showcasing my projects and social media links.
theme: minima

# Build settings
markdown: kramdown
permalink: pretty

# Social media links
social:
  - name: LinkedIn
    url: https://www.linkedin.com/in/yourprofile
  - name: Twitter
    url: https://twitter.com/yourprofile
  - name: GitHub
    url: https://github.com/yourusername